package main

import (
	"context"
	"flag"
	"fmt"
	"strings"

	"github.com/noopolis/moltnet/internal/app"
	"github.com/noopolis/moltnet/pkg/protocol"
)

// runPairJoin implements `moltnet pair <invite-code>`: it consumes an
// invite generated by `moltnet pair invite` on another network and never
// contacts the relay or Cloudflare.
func runPairJoin(ctx context.Context, args []string) error {
	flagArgs, code, err := splitPairJoinArgs(args)
	if err != nil {
		return err
	}

	flags := flag.NewFlagSet("moltnet pair", flag.ContinueOnError)
	flags.SetOutput(stdout)

	var (
		force      = flags.Bool("force", false, "overwrite an existing pairing with the same id")
		configPath = flags.String("config", "", "Moltnet config path")
		networkID  = flags.String("id", "", "network id to select under ~/.moltnet when several exist")
		restart    = flags.Bool("restart", false, "restart the managed service when one exists for the resolved network")
	)

	if err := flags.Parse(flagArgs); err != nil {
		return err
	}
	if code == "" {
		return fmt.Errorf("pair requires exactly one invite code")
	}

	invite, err := protocol.DecodeInvite(code)
	if err != nil {
		return err
	}

	path, err := resolvePairConfigPath(*configPath, *networkID)
	if err != nil {
		return err
	}
	config, err := app.LoadConfigForPath(path, "")
	if err != nil {
		return err
	}

	if invite.NetworkID == config.NetworkID {
		return fmt.Errorf(
			"invite network id %q collides with the local network id in %s; ask the sender to regenerate the invite with a distinct network.id, or change your own, then retry",
			invite.NetworkID, path,
		)
	}

	pairing := app.PairingWriteback{
		ID:                invite.PairingID,
		RemoteNetworkID:   invite.NetworkID,
		RemoteNetworkName: invite.NetworkName,
		Token:             invite.PairingToken,
		Relay: &app.PairingRelayWriteback{
			URL:   invite.RelayURL,
			Room:  invite.Room,
			Token: invite.RelayToken,
		},
	}
	authToken := app.AuthTokenWriteback{
		ID:      invite.PairingID,
		Value:   invite.PairingToken,
		Network: invite.NetworkID,
		Scopes:  []string{"pair"},
	}

	if err := writePairingWithRollback(path, pairing, authToken, invite.SharedRooms, *force); err != nil {
		// ErrPairingExists already carries a "rerun with --force" hint from
		// WritePairing, and --force here is the same flag name, so there is
		// nothing to add.
		return err
	}

	return printPairJoinAftercare(ctx, config, path, pairing.ID, pairAftercareOptions{
		restart:           *restart,
		roomIDs:           invite.SharedRooms,
		remoteNetworkID:   invite.NetworkID,
		remoteNetworkName: invite.NetworkName,
	})
}

// splitPairJoinArgs separates the invite code positional argument from
// `--force`/`--config`/`--id`/`--restart` flags regardless of order, since
// Go's flag package stops parsing at the first non-flag token and the
// invite code is always the first argument in the documented UX (`moltnet
// pair <invite-code>`).
func splitPairJoinArgs(args []string) ([]string, string, error) {
	flagArgs := make([]string, 0, len(args))
	code := ""

	for index := 0; index < len(args); index++ {
		arg := args[index]
		if arg == "--config" || arg == "--id" {
			if index+1 >= len(args) {
				return nil, "", fmt.Errorf("flag %s requires a value", arg)
			}
			flagArgs = append(flagArgs, arg, args[index+1])
			index++
			continue
		}
		if strings.HasPrefix(arg, "-") {
			flagArgs = append(flagArgs, arg)
			continue
		}
		if code != "" {
			return nil, "", fmt.Errorf("pair accepts exactly one invite code")
		}
		code = arg
	}

	return flagArgs, code, nil
}
