package transport

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	authn "github.com/noopolis/moltnet/internal/auth"
	"github.com/noopolis/moltnet/pkg/protocol"
)

func TestDiscoveryRoutesOpenMode(t *testing.T) {
	t.Parallel()

	policy, err := authn.NewPolicy(authn.Config{
		Mode: authn.ModeOpen,
	})
	if err != nil {
		t.Fatalf("NewPolicy() error = %v", err)
	}
	handler := NewHTTPHandler(&fakeService{
		network: protocol.Network{
			ID:   "local_lab",
			Name: "Local Lab",
			Capabilities: protocol.NetworkCapabilities{
				DirectMessages: false,
			},
		},
		rooms: []protocol.Room{
			{ID: "lab", Name: "Lab"},
			{ID: "workshop", Name: "Workshop"},
		},
	}, policy)

	t.Run("install markdown", func(t *testing.T) {
		response := httptest.NewRecorder()
		request := httptest.NewRequest(http.MethodGet, "http://127.0.0.1:19888/install.md", nil)
		handler.ServeHTTP(response, request)

		if response.Code != http.StatusOK {
			t.Fatalf("unexpected status %d", response.Code)
		}
		body := response.Body.String()
		for _, want := range []string{
			"# Join Local Lab Moltnet",
			"You are reading instructions generated by this Moltnet network",
			"## If you should stay connected",
			"A `MoltnetNode` is a YAML file.",
			"One `MoltnetNode` can contain more than one attachment",
			"Choose exactly one path",
			"does not run a background bridge",
			"https://moltnet.dev/llms.txt",
			"http://127.0.0.1:19888/llms.txt",
			"https://moltnet.dev/docs/reference/node-config.md",
			"https://moltnet.dev/docs/guides/runtimes-and-attachments.md",
			"https://moltnet.dev/docs/reference/runtime-capabilities.md",
			"https://moltnet.dev/docs/reference/native-attachment-protocol.md",
			"kind: codex",
			"command: codex",
			"kind: claude-code",
			"command: claude",
			"kind: openclaw",
			`gateway_url: "ws://127.0.0.1:18789"`,
			"kind: picoclaw",
			`events_url: "ws://127.0.0.1:18990/pico/ws"`,
			"kind: tinyclaw",
			`channel: moltnet`,
			`inbound_url: "http://127.0.0.1:3777/api/message"`,
			`outbound_url: "http://127.0.0.1:3777/api/responses/pending?channel=moltnet"`,
			`ack_url: "http://127.0.0.1:3777/api/responses"`,
			`token_path: ".moltnet/<agent-id>.token"`,
			"moltnet node start ./MoltnetNode",
			"## If you only want on-demand access",
			"--base-url http://127.0.0.1:19888",
			"--network-id local_lab",
			"--rooms lab,workshop",
			"--registration open",
			"moltnet read --network local_lab --target room:lab",
			"http://127.0.0.1:19888/skill.md",
		} {
			if !strings.Contains(body, want) {
				t.Fatalf("install markdown missing %q\n%s", want, body)
			}
		}
		if contentType := response.Header().Get("Content-Type"); !strings.Contains(contentType, "text/markdown") {
			t.Fatalf("unexpected content type %q", contentType)
		}
	})

	t.Run("skill markdown", func(t *testing.T) {
		response := httptest.NewRecorder()
		request := httptest.NewRequest(http.MethodGet, "/skill.md", nil)
		handler.ServeHTTP(response, request)

		if response.Code != http.StatusOK {
			t.Fatalf("unexpected status %d", response.Code)
		}
		body := response.Body.String()
		for _, want := range []string{
			"name: moltnet",
			"Current access: public read access",
			"Readable rooms: `lab`, `workshop`",
			"Direct messages are disabled",
			"moltnet read --network local_lab --target room:lab --limit 20",
			"--registration open",
		} {
			if !strings.Contains(body, want) {
				t.Fatalf("skill markdown missing %q\n%s", want, body)
			}
		}
		if strings.Contains(body, "moltnet send --network local_lab --target room:lab") {
			t.Fatalf("open public skill should not expose send for member-default rooms\n%s", body)
		}
		if strings.Contains(body, "moltnet admin agent remove --base-url") {
			t.Fatalf("open public skill should not expose admin command\n%s", body)
		}
	})

	t.Run("llms text", func(t *testing.T) {
		response := httptest.NewRecorder()
		request := httptest.NewRequest(http.MethodGet, "http://internal/llms.txt", nil)
		request.Header.Set("X-Forwarded-Proto", "http")
		request.Header.Set("X-Forwarded-Host", "127.0.0.1:19888")
		handler.ServeHTTP(response, request)

		if response.Code != http.StatusOK {
			t.Fatalf("unexpected status %d", response.Code)
		}
		body := response.Body.String()
		for _, want := range []string{
			"# Local Lab Moltnet",
			"http://127.0.0.1:19888/install.md",
			"http://127.0.0.1:19888/skill.md",
			"http://127.0.0.1:19888/console/",
		} {
			if !strings.Contains(body, want) {
				t.Fatalf("llms text missing %q\n%s", want, body)
			}
		}
	})
}

func TestDiscoveryRoutesRequireObserveWhenBearerProtected(t *testing.T) {
	t.Parallel()

	policy, err := authn.NewPolicy(authn.Config{
		Mode: authn.ModeBearer,
		Tokens: []authn.TokenConfig{
			{ID: "observer", Value: "observe-secret", Scopes: []authn.Scope{authn.ScopeObserve}},
			{ID: "admin", Value: "admin-secret", Scopes: []authn.Scope{authn.ScopeAdmin}},
		},
	})
	if err != nil {
		t.Fatalf("NewPolicy() error = %v", err)
	}
	handler := NewHTTPHandler(&fakeService{
		network: protocol.Network{ID: "private"},
		rooms:   []protocol.Room{{ID: "ops", Name: "Ops"}},
	}, policy)

	response := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodGet, "/install.md", nil)
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusUnauthorized {
		t.Fatalf("expected unauthorized install guide, got %d", response.Code)
	}

	response = httptest.NewRecorder()
	request = httptest.NewRequest(http.MethodGet, "/install.md", nil)
	request.Header.Set("Authorization", "Bearer observe-secret")
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("expected authorized install guide, got %d", response.Code)
	}

	response = httptest.NewRecorder()
	request = httptest.NewRequest(http.MethodGet, "/install.md", nil)
	request.Header.Set("Authorization", "Bearer admin-secret")
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("expected admin install guide, got %d", response.Code)
	}

	response = httptest.NewRecorder()
	request = httptest.NewRequest(http.MethodGet, "/llms.txt", nil)
	request.Header.Set("Authorization", "Bearer admin-secret")
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("expected admin llms text, got %d", response.Code)
	}

	response = httptest.NewRecorder()
	request = httptest.NewRequest(http.MethodGet, "/skill.md", nil)
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusUnauthorized {
		t.Fatalf("expected unauthorized skill, got %d", response.Code)
	}

	response = httptest.NewRecorder()
	request = httptest.NewRequest(http.MethodGet, "/skill.md", nil)
	request.Header.Set("Authorization", "Bearer observe-secret")
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("expected authorized skill, got %d", response.Code)
	}
	body := response.Body.String()
	if !strings.Contains(body, "Current access: read-only access") ||
		!strings.Contains(body, "Read recent room history:") ||
		strings.Contains(body, "Send to a room:") ||
		strings.Contains(body, "moltnet admin agent remove --base-url") {
		t.Fatalf("unexpected observe-only skill\n%s", body)
	}
}

func TestSkillRouteUsesBearerTokenCapabilities(t *testing.T) {
	t.Parallel()

	policy, err := authn.NewPolicy(authn.Config{
		Mode: authn.ModeBearer,
		Tokens: []authn.TokenConfig{
			{ID: "writer", Value: "write-secret", Scopes: []authn.Scope{authn.ScopeWrite}},
			{ID: "admin", Value: "admin-secret", Scopes: []authn.Scope{authn.ScopeAdmin}},
		},
	})
	if err != nil {
		t.Fatalf("NewPolicy() error = %v", err)
	}
	service := &fakeService{
		network: protocol.Network{
			ID:   "private",
			Name: "Private",
			Capabilities: protocol.NetworkCapabilities{
				DirectMessages: true,
			},
		},
		rooms: []protocol.Room{{ID: "hidden", Name: "Hidden"}},
	}
	handler := NewHTTPHandler(service, policy)

	response := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodGet, "/skill.md", nil)
	request.Header.Set("Authorization", "Bearer write-secret")
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("expected writer skill, got %d", response.Code)
	}
	body := response.Body.String()
	if !strings.Contains(body, "Current access: write-only access") ||
		!strings.Contains(body, "Readable rooms: unavailable with this token") ||
		!strings.Contains(body, "Send commands are not available with the current access") ||
		strings.Contains(body, "Read recent room history:") {
		t.Fatalf("unexpected write-only skill\n%s", body)
	}
	if service.limit != 0 {
		t.Fatalf("write-only skill should not list rooms, got limit %d", service.limit)
	}

	response = httptest.NewRecorder()
	request = httptest.NewRequest(http.MethodGet, "/skill.md", nil)
	request.Header.Set("Authorization", "Bearer admin-secret")
	handler.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("expected admin skill, got %d", response.Code)
	}
	if body := response.Body.String(); !strings.Contains(body, "Current access: admin access") ||
		!strings.Contains(body, "moltnet admin agent remove --base-url") {
		t.Fatalf("unexpected admin skill\n%s", body)
	}
}
