package updater

import (
	"context"
	"fmt"
	"os/exec"
	"strings"
)

// CommandRunner executes one external command (git or make) rooted at dir
// and returns its combined output. Production code uses
// defaultCommandRunner; tests inject a fake so they never touch a real git
// binary or a real make against the checkout this package lives in.
type CommandRunner interface {
	Run(ctx context.Context, dir string, name string, args ...string) ([]byte, error)
}

type defaultCommandRunner struct{}

func (defaultCommandRunner) Run(ctx context.Context, dir string, name string, args ...string) ([]byte, error) {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	output, err := command.CombinedOutput()
	if err != nil {
		return output, fmt.Errorf("%s %s: %w", name, strings.Join(args, " "), err)
	}
	return output, nil
}

// gitCheckoutStatus is what a source update needs to know about a stamped
// checkout before deciding whether it is safe to mutate.
type gitCheckoutStatus struct {
	Branch         string
	Clean          bool
	Detached       bool
	LocalCommit    string
	UpstreamCommit string
	UpstreamKnown  bool
}

// generatedWebDistPathspec excludes the tracked `web/dist` directory from
// the working-tree cleanliness check. `web/dist` is vite's build output,
// re-included by web/.gitignore so `go build` works without npm — but that
// also means `make build`'s `console-build` step (vite's emptyOutDir)
// regenerates it on every rebuild. Without this exclusion, the very
// `make build` a source update runs to verify the rebuild works would dirty
// the tree it required to be clean, permanently blocking every update after
// the first. No other tracked path is generated by the build, so this is
// the only exclusion needed.
const generatedWebDistPathspec = ":!web/dist"

// commandOutputTail returns the last maxLines lines of a failed command's
// combined stdout/stderr, so a wrapped error carries the operator-visible
// reason (a compile error, a merge conflict, ...) instead of just the bare
// "exit status 2" an *exec.ExitError.Error() gives on its own.
func commandOutputTail(output []byte, maxLines int) string {
	text := strings.TrimSpace(string(output))
	if text == "" {
		return ""
	}
	lines := strings.Split(text, "\n")
	if len(lines) > maxLines {
		lines = lines[len(lines)-maxLines:]
	}
	return strings.Join(lines, "\n")
}

// wrapCommandError appends output's last few lines to err, when there are
// any, so the diagnostic that reaches the operator is never just the bare
// exit status a failed git/make invocation returns on its own.
func wrapCommandError(err error, output []byte) error {
	if err == nil {
		return nil
	}
	if tail := commandOutputTail(output, 20); tail != "" {
		return fmt.Errorf("%w\n%s", err, tail)
	}
	return err
}

// isGitCheckout reports whether checkout is a directory git recognizes as a
// work tree. A source build stamped with a checkout path that has since
// been moved, deleted, or was never a git repository fails this check, and
// the caller degrades to the plain "install a release tarball" refusal.
func isGitCheckout(ctx context.Context, runner CommandRunner, checkout string) bool {
	output, err := runner.Run(ctx, checkout, "git", "rev-parse", "--is-inside-work-tree")
	return err == nil && strings.TrimSpace(string(output)) == "true"
}

// inspectGitCheckout gathers the branch, working-tree cleanliness, and
// local/upstream commits for checkout. It never mutates the checkout: every
// git subcommand it runs is read-only (it does not fetch — callers that need
// an up-to-date upstream comparison must call gitFetch first).
func inspectGitCheckout(ctx context.Context, runner CommandRunner, checkout string) (gitCheckoutStatus, error) {
	var status gitCheckoutStatus
	if !isGitCheckout(ctx, runner, checkout) {
		return status, fmt.Errorf("%q is not a git checkout", checkout)
	}

	branchOutput, err := runner.Run(ctx, checkout, "git", "rev-parse", "--abbrev-ref", "HEAD")
	if err != nil {
		return status, fmt.Errorf("determine current branch: %w", wrapCommandError(err, branchOutput))
	}
	status.Branch = strings.TrimSpace(string(branchOutput))
	status.Detached = status.Branch == "HEAD"

	// generatedWebDistPathspec excludes web/dist (see its doc comment): a
	// tracked build artifact `make build` regenerates, not a source change.
	statusOutput, err := runner.Run(ctx, checkout, "git", "status", "--porcelain", "--", ".", generatedWebDistPathspec)
	if err != nil {
		return status, fmt.Errorf("check working tree status: %w", wrapCommandError(err, statusOutput))
	}
	status.Clean = strings.TrimSpace(string(statusOutput)) == ""

	localOutput, err := runner.Run(ctx, checkout, "git", "rev-parse", "HEAD")
	if err != nil {
		return status, fmt.Errorf("determine current commit: %w", wrapCommandError(err, localOutput))
	}
	status.LocalCommit = strings.TrimSpace(string(localOutput))

	upstreamOutput, err := runner.Run(ctx, checkout, "git", "rev-parse", "@{u}")
	if err == nil {
		status.UpstreamKnown = true
		status.UpstreamCommit = strings.TrimSpace(string(upstreamOutput))
	}

	return status, nil
}

// gitFetch runs `git fetch` in checkout: it updates remote-tracking refs
// (like @{u}, which inspectGitCheckout reads) but never touches the working
// tree or the current branch, so it is safe to run before a real update has
// decided whether it is allowed to mutate anything. Callers that skip this
// — the original bug this fixes — compare against whatever @{u} happened to
// point at after the last unrelated fetch (a prior `git pull`, an editor's
// background fetch, ...), which can be arbitrarily stale and makes an
// available update permanently invisible.
func gitFetch(ctx context.Context, runner CommandRunner, checkout string) error {
	output, err := runner.Run(ctx, checkout, "git", "fetch")
	return wrapCommandError(err, output)
}

// gitPullFastForward runs `git pull --ff-only` in checkout. Callers must
// have already verified the working tree is clean and on a branch;
// --ff-only refuses to create a merge commit, so a diverged local branch
// fails loudly here instead of silently merging.
func gitPullFastForward(ctx context.Context, runner CommandRunner, checkout string) error {
	output, err := runner.Run(ctx, checkout, "git", "pull", "--ff-only")
	return wrapCommandError(err, output)
}

// runMakeBuild runs `make build` in checkout, reusing the project's own
// build target (Makefile) instead of reimplementing the go build invocation
// here. It produces bin/moltnet under checkout, same as a manual `make
// build` run by a developer.
func runMakeBuild(ctx context.Context, runner CommandRunner, checkout string) error {
	output, err := runner.Run(ctx, checkout, "make", "build")
	return wrapCommandError(err, output)
}
